version: '3.9'

services:
  oracle:
    container_name: oracle-xe
    image: 'gvenzl/oracle-xe:latest'
    environment:
      - ORACLE_PASSWORD=password
    ports:
      - "1521:1521"
    restart: unless-stopped
