version: "3.9"
services:
  jomma-ltd:
    image: oracle/database:19.3.0-ee
    container_name: jomma-ltd
    ports:
      - "1521:1521"
    ulimits:
      nofile:
        soft: 1024
        hard: 65536
      nproc:
        soft: 2047
        hard: 16384
      stack:
        soft: 10485760
        hard: 33554432
      memlock:
        soft: 3221225472
        hard: 3221225472
    environment:
      - ORACLE_SID=oracle19
      - ORACLE_PDB=oracledb
      - ORACLE_PWD=p@ass9woRd
      - ORACLE_EDITION=enterprise
      - ORACLE_CHARACTERSET=AL32UTF8
      - ENABLE_ARCHIVELOG=true
      - ENABLE_TCPS=true
      - ORACLE_BASE=/opt/oracle
    volumes:
      - ./data:/opt/oracle/oradata
